# -*- coding: utf-8 -*-
"""02. Lists.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yWGjq3Tp7fHSV_CPv2JIhWL0qLGl5Jjx
"""

"""
Ejercicio 1

Escribir un programa que almacene las asignaturas de un curso
(por ejemplo Matemáticas, Física, Química, Historia y Lengua) en una lista y la
 muestre por pantalla.
"""
subjects = ["Math", "Physical", "Chemistry", "History", "Languaje"]
print(subjects)

"""
Ejercicio 2

Escribir un programa que almacene las asignaturas de un curso
(por ejemplo Matemáticas, Física, Química, Historia y Lengua) en una lista y la
muestre por pantalla el mensaje Yo estudio <asignatura>, donde <asignatura> es
cada una de las asignaturas de la lista.
"""
for subject in subjects:
  print("I study", subject)

"""
Ejercicio 3

Escribir un programa que almacene las asignaturas de un curso (por ejemplo
Matemáticas, Física, Química, Historia y Lengua) en una lista, pregunte al
usuario la nota que ha sacado en cada asignatura, y después las muestre por
pantalla con el mensaje En <asignatura> has sacado <nota> donde <asignatura>
es cada una des las asignaturas de la lista y <nota> cada una de las
correspondientes notas introducidas por el usuario.
"""
grades = []
for subject in subjects:
  grade = input(f'¿What grade have you get in {subject}?')
  grades.append(grade)

for subject, grade in zip(subjects, grades):
  print(f'In {subject} you have a grade of {grade}')

"""
Ejercicio 4

Escribir un programa que pregunte al usuario los números ganadores de la lotería
primitiva, los almacene en una lista y los muestre por pantalla ordenados de
menor a mayor.
"""
numbers = []

for i in range(6):
  number = input(f'¿What is the number {i+1}?  -> ')
  numbers.append(number)

print('')
print(sorted(numbers))

"""
Ejercicio 5

Escribir un programa que almacene en una lista los números del 1 al 10 y los
muestre por pantalla en orden inverso separados por comas.
"""
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
for i in range(1, 11):
    print(numbers[-i], end=", ")

"""
Ejercicio 6

Escribir un programa que almacene las asignaturas de un curso (por ejemplo
Matemáticas, Física, Química, Historia y Lengua) en una lista, pregunte al
usuario la nota que ha sacado en cada asignatura y elimine de la lista las
asignaturas aprobadas. Al final el programa debe mostrar por pantalla las
asignaturas que el usuario tiene que repetir.
"""
grades = []
for subject in subjects:
  grade = int(input(f'¿What grade have you get in {subject}?  R: '))
  grades.append(grade)

for subject, grade in zip(subjects, grades):
  if grade >= 4:
    print(f'In {subject} you have a grade of {grade}')
    subjects.pop(subject)
print(subjects)

"""
Ejercicio 7

Escribir un programa que almacene el abecedario en una lista, elimine de la
lista las letras que ocupen posiciones múltiplos de 3, y muestre por pantalla
la lista resultante.
"""
alphabet = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
            'n', 'ñ', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y',
            'z']

for i in range(len(alphabet), 1, -1):
    if i % 3 == 0:
        alphabet.pop(i-1)
print(alphabet)

"""
Ejercicio 8

Escribir un programa que pida al usuario una palabra y muestre por pantalla si
es un palíndromo.
"""
word = input('Write a word: ')

list_word = list(word)

list_word_inverse = list(word)
list_word_inverse.reverse()

if list_word == list_word_inverse:
  print(f'{word} is a palindrome')
else:
  print(f'{word} is not a palindrome')

"""
Ejercicio 9

Escribir un programa que pida al usuario una palabra y muestre por pantalla el
número de veces que contiene cada vocal.
"""
vocals = ['a', 'e', 'i', 'o', 'u']
word = input('Write a word: ')
word = list(word)

for vocal in vocals:
  count = 0
  for letter in word:
    if vocal == letter:
      count += 1
  print(f'Vocal {vocal} - {count}')

"""
Ejercicio 10

Escribir un programa que almacene en una lista los siguientes precios,
50, 75, 46, 22, 80, 65, 8, y muestre por pantalla el menor y el mayor de los
precios.
"""
prices = [50, 75, 46, 22, 80, 65, 8]
print(max(prices))
print(min(prices))

"""
Ejercicio 11

Escribir un programa que almacene los vectores (1,2,3) y (-1,0,2) en dos listas
y muestre por pantalla su producto escalar.
"""
a = [1,2,3]
b = [-1,0,2]
product = 0
for i in range(len(a)):
    product += a[i]*b[i]
print(product)